[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]
edit = [
	{ run = 'windsurf "$@"', block = true, for = "unix" },
	{ run = "windsurf %*",  block = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[key]
# Navigation
"j" = "move down"
"k" = "move up"
"h" = "move left"
"l" = "move right"
"gg" = "move top"
"G" = "move bottom"

# File operations
"dd" = "delete"
"yy" = "yank"
"pp" = "paste"
"<enter>" = "open"
"<space>" = "select"

# Toggles
"s" = "toggle linemode"
"z" = "toggle hidden"