working-dir = 'D:' 



env-vars = ["EDITOR=nvim"]


confirm-before-quit = false



[keyboard]
use-kitty-keyboard-protocol = false
disable-ctlseqs-alt = false



placeholder = "‚ùØ"




[cursor]
shape = 'beam'
blinking = false
blinking-interval = 800
hide-if-single = true


[renderer]
performance = "High"
backend = "Automatic"
disable-unfocused-render = false
level = 1
target-fps = 120





[fonts]
family = "MesloLGL Nerd Font"
size = 22
features = ["ss01", "ss02", "ss03", "ss04", "calt", "liga"]
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []
hinting = true

[scroll]
multiplier = 3.0
divider = 1.0


[window]
mode = "Maximized"
blur = true
opacity = 0.5
decorations = "enabled"
width = 600
height = 400
windows-corner-preference = "Round"






[navigation]
mode = "bookmark"
clickable = true
hide-if-single = true
use-split = true
use-current-path = false
color-automation = [
  { program = "nvim", color = "#FFFF00" }
]

[shell]
program = "pwsh"

[platform]
windows.shell.program = "pwsh"
windows.shell.args = []

linux.shell.program = "pwsh"
linux.shell.args = []


[developer]
log-level = "OFF"
enable-log-file = false
